### PR TITLE
fix: prevent batch_index overflow in raw_curp

### LINKED ISSUE #368: Bug: batch_index in raw_curp will overflow eventually
Now `batch_index[i]` is the sum of serialized size of `entries[0..i-1]`.

The `log.compact()` cannot reset the `batch_index`, so it will overflow eventually.

A better way to calculate the batch of log entries is calculate it at `push_back()`.

```rust
struct LogEntryVecDeque<C: Command> {
    entries: VecDeque<LogEntry<C>>,
    entry_size: VecDeque<u64>,
    /// the right index of the batch
    /// batch_range: [i, batch_index[i]]
    batch_index: VecDeque<usize>,
    first_entry_at_last_batch: usize,
    last_batch_size: u64,
    batch_limit: u64,
}
...
    fn push_back(&mut self, entry: LogEntry<C>) -> Result<(), bincode::Error> {
        let entry_size = serialized_size(&entry)?;

        self.entries.push_back(entry);
        self.entry_size.push_back(entry_size);
        self.batch_index.push_back(0)

        while self.last_batch_size + entry_size > self.batch_limit {
            self.batch_index[self.first_entry_at_last_batch] = entries.len() - 1;
            self.last_batch_size = self.last_batch_size - self.entry_size[self.first_entry_at_last_batch];
            self.first_entry_at_last_batch++;
        }
        Ok(())
    }
...
    /// `binary_search` can be optimized in `get_range_by_batch`
    fn get_range_by_batch(&self, left: usize) -> Range<usize> {
        Range<usize>{
            start: left,
            end: self.batch_index[left],
        }
    }
```

### PR DESCRIPTION
**Pull request by GFX9**
* what problem are you trying to solve? (or if there's no problem, what's the motivation for this change?)
-> Fixes #368 

* what changes does this pull request make?
-> Use a scrolling array to replace the previous prefix array to prevent `batch_index ` overflow, which will be truncated when compact. Besides, the scrolling array reduces the operation time complexity of obtaining batch log to O(1).

* are there any non-obvious implications of these changes? (does it break compatibility with previous versions, etc)
-> No

### CODE REVIEW

**Comment by bsbds** [comment]
This implementation is too complex compare to the original prefix sum version. I suggest making some modifications to the original algorithm. Here's the pseudocode. The interval representation is `[left, right)`.

```rust
#[derive(Default)]
struct Log {
    right: Vec<usize>,
    sizes: Vec<u64>,
    limit: u64,
    p: usize,
    sum: u64,
}

impl Log {
    fn push(&mut self, size: u64) {
        self.sizes.push(size);
        self.right.push(0);
        self.sum += size;
        while self.sum > self.limit {
            self.right[self.p] = self.sizes.len() - 1;
            self.sum -= self.sizes[self.p];
            self.p += 1;
        }
    }

    fn get(&self, left: usize) -> usize {
        self.right[left]
    }
}

```

File: crates/curp/src/server/raw_curp/log.rs [hunk 1]
```diff
@@ -82,21 +82,28 @@ impl<C: Command> FallbackContext<C> {
 struct LogEntryVecDeque<C: Command> {
     /// A VecDeque to store log entries, it will be serialized and persisted
     entries: VecDeque<Arc<LogEntry<C>>>,
-    /// The sum of serialized size of previous log entries
-    /// batch_index[i+1] = batch_index[i] + size(entries[i])
-    batch_index: VecDeque<u64>,
+    /// entry size of each item in entries
+    entry_size: VecDeque<u64>,
+    /// the right index of the batch (offset)
+    /// batch_range: [i, i + batch_index[i]]
```
[the remark this answers is not in the document]
Comment (GFX9) [reply crates/curp/src/server/raw_curp/log.rs:88]: Yes, I record the relative index of each element, which simplifies the process of compact because the relevant index is the same when calling `pop_front`.

File: crates/curp/src/server/raw_curp/log.rs [hunk 2]
```diff
@@ -175,15 +238,56 @@ impl<C: Command> LogEntryVecDeque<C> {
...
+        if let Some(&offset) = self.batch_index.get(left) {
+            offset != 0
         } else {
             false
         }
     }
+
+    #[allow(unused)]
+    /// set batch limit and reconstruct `batch_index`
+    fn set_batch_limit(&mut self, batch_limit: u64) {
```
[the remark this answers is not in the document]
Comment (GFX9) [reply crates/curp/src/server/raw_curp/log.rs:250]: I've added `#[cfg(test)]` to the top of this method.

File: crates/curp/src/server/raw_curp/log.rs [hunk 3]
```diff
@@ -111,21 +118,71 @@ impl<C: Command> LogEntryVecDeque<C> {
...
+            self.batch_index[self.first_entry_at_last_batch] =
+                self.entries.len() - self.first_entry_at_last_batch; // record offset but not absolute index
+        }
+
         Ok(())
     }
 
     /// pop a log entry from the front of queue
     fn pop_front(&mut self) -> Option<Arc<LogEntry<C>>> {
+        #![allow(clippy::indexing_slicing)]
```
[the remark this answers is not in the document]
Comment (GFX9) [reply crates/curp/src/server/raw_curp/log.rs:168]: I have checked whether the index is legal in previous `if` statement, so all indexing_slicing is legal and I just use `indexing_slicing` to make the code easy to read.

File: crates/curp/src/server/raw_curp/log.rs [hunk 4]
```diff
@@ -134,36 +191,42 @@ impl<C: Command> LogEntryVecDeque<C> {
...
 
     /// Get the range [left, right) of the log entry, whose size should be equal or smaller than `batch_limit`
     fn get_range_by_batch(&self, left: usize) -> Range<usize> {
-        #[allow(clippy::indexing_slicing)]
-        let target = self.batch_index[left].overflow_add(self.batch_limit);
-        // remove the fake index 0 in `batch_index`
-        match self.batch_index.binary_search(&target) {
-            Ok(right) => left..right,
-            Err(right) => left..right - 1,
+        #![allow(clippy::indexing_slicing)]
```
[the remark this answers is not in the document]
Comment (GFX9) [reply crates/curp/src/server/raw_curp/log.rs:217]: I have checked whether the index is legal in previous `if` statement, so all indexing_slicing is legal and I just use `indexing_slicing` to make the code easy to read.

File: crates/curp/src/server/raw_curp/log.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (Phoenix500526) [reply crates/curp/src/server/raw_curp/log.rs:195]: This is a better way.
```suggestion
    fn pop_front(&mut self) -> Option<Arc<LogEntry<C>>> {
        if let Some(front_size) = self.entry_size.pop_front() {
            if self.first_entry_at_last_batch == 0 {
                self.last_batch_size -= front_size;
            } else {
                self.first_entry_at_last_batch -= 1;
            }
            let _ = self
                .batch_index
                .pop_front()
                .unwrap_or_else(|| unreachable!("The batch_index should not be empty"));
            self.entries.pop_front()
        } else {
            None
        }
    }
```

File: crates/curp/src/server/raw_curp/log.rs [hunk 5]
```diff
@@ -111,21 +118,98 @@ impl<C: Command> LogEntryVecDeque<C> {
...
-            .push_back(pre_entries_size.overflow_add(entry_size));
+        self.entry_size.push_back(entry_size);
+        self.batch_index.push_back(0); // placeholder
+
+        if entry_size > self.batch_limit {
+            self.handle_oversized_entry();
+            return Ok(());
+        }
+
+        while self.last_batch_size + entry_size > self.batch_limit
```
Comment (Phoenix500526) [inline crates/curp/src/server/raw_curp/log.rs:137]: In what situation will this `self.first_entry_at_last_batch >= self.entries.len()` come true?

File: crates/curp/src/server/raw_curp/log.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (Phoenix500526) [reply crates/curp/src/server/raw_curp/log.rs:88]: Why don't you use the `li_to_pi` method to convert a logic index to a physical index?

**Review by Phoenix500526 — CHANGES_REQUESTED** [review]

File: crates/curp/src/server/raw_curp/log.rs [hunk 6]
```diff
@@ -113,19 +120,51 @@ impl<C: Command> LogEntryVecDeque<C> {
...
+            if self.first_entry_at_last_batch == 0 {
+                self.last_batch_size -= front_size;
+            } else {
+                self.first_entry_at_last_batch -= 1;
+            }
+
+            let _ = self
+                .batch_index
+                .pop_front()
+                .unwrap_or_else(|| unreachable!());
```
Comment (Phoenix500526) [inline crates/curp/src/server/raw_curp/log.rs:163]: Please add some messages in this `unreachable!` macro.

File: crates/curp/src/server/raw_curp/log.rs [hunk 7]
```diff
@@ -113,19 +120,51 @@ impl<C: Command> LogEntryVecDeque<C> {
...
+            let _ = self
+                .entry_size
+                .pop_front()
+                .unwrap_or_else(|| unreachable!());
```
Comment (Phoenix500526) [inline crates/curp/src/server/raw_curp/log.rs:167]: Same as above.

File: crates/curp/src/server/raw_curp/log.rs [hunk 8]
```diff
@@ -113,19 +120,51 @@ impl<C: Command> LogEntryVecDeque<C> {
...
-        let Some(&pre_entries_size) = self.batch_index.back() else {
-            unreachable!("batch_index cannot be None")
-        };
-        self.batch_index
-            .push_back(pre_entries_size.overflow_add(entry_size));
+        self.entry_size.push_back(entry_size);
+        self.batch_index.push_back(0); // placeholder
+        self.last_batch_size += entry_size;
+
+        while self.last_batch_size > self.batch_limit {
```
Comment (Phoenix500526) [inline crates/curp/src/server/raw_curp/log.rs:132]: Why do you skip the equal case here?  I think we should update the `batch_index` when the `self.last_batch_size == self.batch_limit`.

File: crates/curp/src/server/raw_curp/log.rs [hunk 9]
```diff
@@ -175,15 +217,32 @@ impl<C: Command> LogEntryVecDeque<C> {
...
-        if let (Some(&cur_size), Some(&last_size)) =
-            (self.batch_index.get(left), self.batch_index.back())
-        {
-            let target_size = cur_size.overflow_add(self.batch_limit);
-            target_size <= last_size
+        if let Some(&offset) = self.batch_index.get(left) {
+            offset != 0
+                || (self.first_entry_at_last_batch == left
+                    && self.batch_limit == self.last_batch_size)
+                || left == self.batch_index.len() - 1
```
Comment (Phoenix500526) [inline crates/curp/src/server/raw_curp/log.rs:224]: Why does the condition `left == self.batch_index.len() - 1` indicates that the log has next batch?

File: crates/curp/src/server/raw_curp/log.rs [hunk 10]
```diff
@@ -134,36 +173,39 @@ impl<C: Command> LogEntryVecDeque<C> {
...
+    #[allow(clippy::range_plus_one)]
     fn get_range_by_batch(&self, left: usize) -> Range<usize> {
-        #[allow(clippy::indexing_slicing)]
-        let target = self.batch_index[left].overflow_add(self.batch_limit);
-        // remove the fake index 0 in `batch_index`
-        match self.batch_index.binary_search(&target) {
-            Ok(right) => left..right,
-            Err(right) => left..right - 1,
+        #![allow(clippy::indexing_slicing)]
+        if left >= self.batch_index.len() {
```
[the remark this answers is not in the document]
Comment (ToniXWD) [reply crates/curp/src/server/raw_curp/log.rs:201]: This is an old implementation, which has been removed noew.

[the remark this answers is not in the document]
Comment (GFX9) [reply crates/curp/src/server/raw_curp/log.rs:201]: This code has been removed now.

File: crates/curp/src/server/raw_curp/log.rs (hunk 6 above)
Comment (GFX9) [reply crates/curp/src/server/raw_curp/log.rs:163]: Done.

File: crates/curp/src/server/raw_curp/log.rs (hunk 7 above)
Comment (GFX9) [reply crates/curp/src/server/raw_curp/log.rs]: Done

File: crates/curp/src/server/raw_curp/log.rs (hunk 8 above)
Comment (GFX9) [reply crates/curp/src/server/raw_curp/log.rs]: The reason for the design is to unify the right index of a range, which are different between `self.last_batch_size > self.batch_limit` and `self.last_batch_size == self.batch_limit`. But I think your explanation makes sense, so I‘ve changed my code.

File: crates/curp/src/server/raw_curp/log.rs (hunk 9 above)
Comment (GFX9) [reply crates/curp/src/server/raw_curp/log.rs]: After the modification above, this part of code has been refactored.

**Comment by GFX9** [comment]
The current implementation uses relevant offset to handle the right index of the `range`. But when `Log` calls methods of `LogEntryVecDeque`, there already exists the process of transferring the logical index to physical index. So the current implementation is kind of redundant, which should be improved in the future.

**Comment by Phoenix500526** [comment]
@Megrifyio rebase

**Comment by Phoenix500526** [comment]
@Mergifyio rebase

File: crates/curp/src/server/raw_curp/log.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (Phoenix500526) [reply crates/curp/src/server/raw_curp/log.rs:88]: I leave an issue #800  to track

**Review by Phoenix500526 — DISMISSED** [review]
LGTM

File: crates/curp/src/server/raw_curp/log.rs [hunk 11]
```diff
@@ -113,19 +120,57 @@ impl<C: Command> LogEntryVecDeque<C> {
...
+                    // self.last_batch_size == self.batch_limit means the last index must be included in `get_range`
+                    *cur_batch_index += 1;
+                }
+
+                if let Some(cur_entry_size) = self.entry_size.get(self.first_entry_at_last_batch) {
+                    self.last_batch_size -= *cur_entry_size;
+                }
+                self.first_entry_at_last_batch += 1;
+            }
+        }
```
Comment (bsbds) [inline crates/curp/src/server/raw_curp/log.rs:147]: Please try simpify this procedure, base on previous comment: https://github.com/xline-kv/Xline/pull/704#issuecomment-2034304554

File: crates/curp/src/server/raw_curp/log.rs [hunk 12]
```diff
@@ -134,36 +179,39 @@ impl<C: Command> LogEntryVecDeque<C> {
...
+        #![allow(clippy::indexing_slicing)]
+        if left >= self.batch_index.len() {
+            left..self.entries.len()
+        } else if self.entry_size[left] > self.batch_limit {
+            left..left + 1
+        } else if self.batch_index[left] == 0 {
+            left..self.entries.len()
+        } else {
+            left..left + self.batch_index[left]
         }
```
Comment (bsbds) [inline crates/curp/src/server/raw_curp/log.rs:215]: There's too much if-else statements, please consider refactor this and merge the conditions.

Comment (Phoenix500526) [reply crates/curp/src/server/raw_curp/log.rs]: Done

File: crates/curp/src/server/raw_curp/log.rs (hunk 11 above)
Comment (Phoenix500526) [reply crates/curp/src/server/raw_curp/log.rs]: It's simpler now

File: crates/curp/src/log_entry.rs [hunk 13]
```diff
@@ -23,6 +23,8 @@ pub struct LogEntry<C> {
     pub(crate) propose_id: ProposeId,
     /// Entry data
     pub(crate) entry_data: EntryData<C>,
+    /// entry size
+    pub(crate) size: u64,
```
Comment (bsbds) [inline crates/curp/src/log_entry.rs:27]: I suggest to manually implement the Serialize and Deserialize trait for LogEntry, other wise the size field could occupy some space.

File: crates/curp/src/server/raw_curp/log.rs [hunk 14]
```diff
@@ -23,13 +23,77 @@ use crate::{
...
+/// (`first_idx_in_cur_batch`, `batch_end[first_idx_in_cur_batch]`) = (4, 0), which means the `entries[4..]` is a valid batch (aka. current batch) whose size (aka. `cur_batch_size`) is 3+4+2=9, less than the `batch_limit`
 pub(super) struct Log<C: Command> {
     /// Log entries, should be persisted
+    /// A VecDeque to store log entries, it will be serialized and persisted
     /// Note that the logical index in `LogEntry` is different from physical index
-    entries: LogEntryVecDeque<C>,
+    entries: VecDeque<Arc<LogEntry<C>>>,
+    /// Each element `batch_end[i]` represents the right inclusive bound of a log batch whose size is less than or equal to `batch_limit`
+    /// if you want to fetch a batch which begins at the index `i`, you can fetch it directly by `i..=batch_end[i]`
+    batch_end: VecDeque<LogIndex>,
```
Comment (bsbds) [inline crates/curp/src/server/raw_curp/log.rs:90]: Why not store physical index in batch_end directly?

File: crates/curp/src/server/raw_curp/log.rs [hunk 15]
```diff
@@ -23,13 +23,77 @@ use crate::{
...
+/// `entry_size[i]`| 1 | 5 | 6 | 2 | 3 | 4 | 2 |
+/// ---------------+---------------------------+
+/// i              | 0 | 1 | 2 | 3 | 4 | 5 | 6 |
+/// ---------------+---+---+---+---+---+---+---+
+/// `batch_end[i]` | 1 | 2 | 4 | 5 | 0 | 0 | 0 |
+/// -------------------------------------------
+///                                  ↑
+///                       `first_idx_in_cur_batch`
+/// (0, `batch_end[0]`) = (0,1), which means the `entries[0..=1]` is a valid batch whose size is 1+5=6, less than the `batch_limit`
+/// (1, `batch_end[1]`) = (1,2), which means the `entries[1..=2]` is a valid batch whose size is 5+6=11, equal to the `batch_limit`
```
Comment (bsbds) [inline crates/curp/src/server/raw_curp/log.rs:80]: I think making the batch_end exclusive could simplified the code even further, for instance batch_end[0] = 1 means entries[0..1]. Please refer to https://github.com/xline-kv/Xline/pull/704#issuecomment-2034304554

File: crates/curp/src/server/raw_curp/log.rs (hunk 14 above)
Comment (Phoenix500526) [reply crates/curp/src/server/raw_curp/log.rs:90]: If you compact the log, the physical index will be changed.

File: crates/curp/src/log_entry.rs (hunk 13 above)
Comment (Phoenix500526) [reply crates/curp/src/log_entry.rs:27]: I move the size field out of LogEntry and wrap it with entry in a new Entry struct.

**Review by bsbds — APPROVED** [review]

**Review by rogercloud — APPROVED** [review]
